---
- name: fishをインストール
  community.general.homebrew:
    name: fish
    state: latest
    update_homebrew: true

- name: fishを選択可能なシェルとして追加
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/fish
  become: true

- name: 現在のデフォルトシェルを取得
  ansible.builtin.command: dscl . -read /Users/{{ ansible_user_id }} UserShell
  register: fish_current_shell_raw
  become: true
  changed_when: false

- name: 現在のシェルを整形
  ansible.builtin.set_fact:
    fish_current_shell: "{{ fish_current_shell_raw.stdout.split(' ')[-1] }}"

- name: fishをデフォルトのシェルにする (macOS用)
  ansible.builtin.command: dscl . -change /Users/{{ ansible_user_id }} UserShell {{ fish_current_shell }} /opt/homebrew/bin/fish
  become: true
  when: fish_current_shell != "/opt/homebrew/bin/fish"
  changed_when: false

- name: fish completionsのインストール先を作成
  ansible.builtin.file:
    path: ~/.config/fish/completions
    state: directory
    mode: "0755"

- name: helm completionsをインストール
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/fish-shell/fish-shell/master/share/completions/helm.fish
    dest: ~/.config/fish/completions/helm.fish
    mode: "0644"

- name: bun completionsをインストール
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/oven-sh/bun/main/completions/bun.fish
    dest: ~/.config/fish/completions/bun.fish
    mode: "0644"

- name: fisherのインストール先を作成
  ansible.builtin.file:
    path: ~/.config/fish/functions
    state: directory
    mode: "0755"

- name: fisherをインストール
  ansible.builtin.get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish
    mode: "0644"

- name: Powerline fontsのインストールをチェック
  ansible.builtin.shell: ls ~/Library/Fonts/*Powerline.ttf
  register: fish_fonts_ls_result
  failed_when: false
  changed_when: false

- name: Powerline fontsをclone
  ansible.builtin.git:
    repo: https://github.com/powerline/fonts.git
    dest: /tmp/powerlinefonts
    depth: 1
    version: master
  when: fish_fonts_ls_result.rc != 0

- name: Powerline fontsをインストール
  ansible.builtin.command: /tmp/powerlinefonts/install.sh
  when: fish_fonts_ls_result.rc != 0
  changed_when: false

- name: Powerline fontsをクリーン
  ansible.builtin.file:
    path: /tmp/powerlinefonts
    state: absent

- name: fishのパッケージファイルを更新
  ansible.builtin.copy:
    dest: ~/.config/fish/fish_plugins
    content: "{{ fish_packages }}"
    mode: "0644"

- name: fishのパッケージを更新
  ansible.builtin.command: fish -c "fisher update"
  changed_when: false
