- name: fishをインストール
  homebrew:
    name: fish
    state: latest
    update_homebrew: true

- name: fishを選択可能なシェルとして追加
  lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/fish
  become: true

- name: 現在のデフォルトシェルを取得
  command: dscl . -read /Users/{{ ansible_user_id }} UserShell
  register: current_shell_raw
  become: true

- name: 現在のシェルを整形
  set_fact:
    current_shell: "{{ current_shell_raw.stdout.split(' ')[-1] }}"

- name: fishをデフォルトのシェルにする (macOS用)
  shell: dscl . -change /Users/{{ ansible_user_id }} UserShell {{ current_shell }} /opt/homebrew/bin/fish
  become: true
  when: current_shell != "/opt/homebrew/bin/fish"

- name: fish completionsのインストール先を作成
  file:
    path: ~/.config/fish/completions
    state: directory

- name: helm completionsをインストール
  get_url:
    url: https://raw.githubusercontent.com/fish-shell/fish-shell/master/share/completions/helm.fish
    dest: ~/.config/fish/completions/helm.fish

- name: bun completionsをインストール
  get_url:
    url: https://raw.githubusercontent.com/oven-sh/bun/main/completions/bun.fish
    dest: ~/.config/fish/completions/bun.fish

- name: fisherのインストール先を作成
  file:
    path: ~/.config/fish/functions
    state: directory

- name: fisherをインストール
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish

- name: Powerline fontsのインストールをチェック
  shell: ls ~/Library/Fonts/*Powerline.ttf
  register: fonts_ls_result
  failed_when: false
  changed_when: false

- name: Powerline fontsをclone
  git:
    repo: https://github.com/powerline/fonts.git
    dest: /tmp/powerlinefonts
    depth: 1
  when: fonts_ls_result.rc != 0

- name: Powerline fontsをインストール
  shell: /tmp/powerlinefonts/install.sh
  when: fonts_ls_result.rc != 0

- name: Powerline fontsをクリーン
  file:
    path: /tmp/powerlinefonts
    state: absent

- name: fishのパッケージファイルを更新
  copy:
    dest: ~/.config/fish/fish_plugins
    content: "{{ fish_packages }}"

- name: fishのパッケージを更新
  shell: fish -c "fisher update"
  changed_when: false
