---
- name: macOSセットアップ
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: community.generalをインストール
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r requirements.yml -p ~/.ansible/collections
      changed_when: false
      delegate_to: localhost

  roles:
    - { role: fish, tags: fish }
    - { role: vscode, tags: vscode }
    - { role: dotfiles, tags: dotfiles }
    - { role: osx_defaults, tags: osx_defaults }
    - { role: homebrew, tags: homebrew }
    - { role: mise, tags: mise }
