---
- name: dotfilesをclone
  ansible.builtin.git:
    repo: git@github.com:u1aryz/dotfiles.git
    dest: ~/.config/dotfiles
    version: main
    update: false

# リンクのマッピングはdotfilesリポジトリ側のlink.shが管理する
- name: link.shでシンボリックリンクを作成
  ansible.builtin.command:
    cmd: sh {{ ansible_facts['env']['HOME'] }}/.config/dotfiles/link.sh
  register: dotfiles_link_result
  changed_when: dotfiles_link_result.stdout | length > 0
