---
- name: homebrewのtabリポジトリを追加
  community.general.homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: homebrewをアップデート
  community.general.homebrew:
    update_homebrew: true

- name: brewパッケージをインストール
  community.general.homebrew:
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ homebrew_packages }}"

- name: ログイン時にColimaを自動起動する
  community.general.homebrew_services:
    name: colima
    state: present

- name: caskパッケージをインストール
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    state: installed
    install_options: "appdir=/Applications,no-quarantine"
  become: true
  failed_when: false
  with_items: "{{ homebrew_cask_packages }}"
