---
- name: homebrewをアップデート
  community.general.homebrew:
    update_homebrew: true

- name: brewパッケージをインストール
  community.general.homebrew:
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ homebrew_packages }}"

- name: パスワードなしsudoを一時的に許可してcaskインストール
  block:
    - name: パスワードなしでsudoを許可
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ user }}-homebrew-nopasswd"
        content: "{{ user }} ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: wheel
        mode: "0440"
        validate: /usr/sbin/visudo -cf %s
      become: true
      changed_when: false
    - name: caskパッケージをインストール
      community.general.homebrew_cask:
        name: "{{ item.name }}"
        state: installed
        install_options: "appdir=/Applications"
      failed_when: false
      with_items: "{{ homebrew_cask_packages }}"
  always:
    - name: パスワードなしでsudoを許可の設定を削除
      ansible.builtin.file:
        path: "/etc/sudoers.d/{{ user }}-homebrew-nopasswd"
        state: absent
      become: true
      changed_when: false
