- name: homebrewのtabリポジトリを追加
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: homebrewをアップデート
  homebrew:
    update_homebrew: true

- name: brewパッケージをインストール
  homebrew:
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ homebrew_packages }}"

- name: ログイン時にColimaを自動起動する
  community.general.homebrew_services:
    name: colima
    state: present

- block:
  - name: パスワードなしでsudoを許可
    lineinfile:
      path: /etc/sudoers
      line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
    become: true
    changed_when: false
  - name: caskパッケージをインストール
    homebrew_cask:
      name: "{{ item.name }}"
      state: installed
      install_options: "appdir=/Applications"
    failed_when: false
    with_items: "{{ homebrew_cask_packages }}"
  always:
  - name: パスワードなしでsudoを許可の設定を削除
    lineinfile:
      path: /etc/sudoers
      line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
      state: absent
    become: true
    changed_when: false
