---
homebrew_trusted_taps:
  - dart-lang/dart
  - leoafarias/fvm
  - fastly/tap
  - oven-sh/bun
  - hashicorp/tap
homebrew_packages:
  - { name: gcc }
  - { name: git }
  - { name: mercurial }
  - { name: tree }
  - { name: wget }
  - { name: tmux }
  - { name: curl }
  - { name: ghq }
  - { name: fzf }
  - { name: fish }
  - { name: openssl }
  - { name: fontconfig }
  - { name: reattach-to-user-namespace }
  - { name: fx }
  - { name: kubectl }
  - { name: minikube }
  - { name: helm }
  - { name: dart-lang/dart/dart }
  - { name: leoafarias/fvm/fvm }
  - { name: lolcat }
  - { name: cloudflared }
  - { name: eza }
  - { name: rust }
  - { name: ripgrep }
  - { name: bat }
  - { name: fd }
  - { name: mise }
  - { name: coreutils }
  - { name: zellij }
  - { name: usage }
  - { name: fastly/tap/fastly }
  - { name: websocat }
  - { name: noti }
  - { name: ghostty }
  - { name: prettier }
  - { name: yamlfmt }
  - { name: docker }
  - { name: docker-compose }
  - { name: docker-buildx }
  - { name: dockerfmt }
  - { name: ansible-lint }
  - { name: ffmpeg }
  - { name: taplo }
  - { name: awscli }
  - { name: graphviz }
  - { name: yt-dlp }
  - { name: codex }
  - { name: hashicorp/tap/terraform }
  - { name: gh }
  - { name: lazydocker }
  - { name: oven-sh/bun/bun }
  - { name: mactop }
  - { name: orbstack }
  - { name: cloc }
  - { name: openjdk }
  - { name: container }
  - { name: herdr }
  - { name: hunk }
homebrew_cask_packages:
  - { name: raycast }
  - { name: google-chrome }
  - { name: google-cloud-sdk }
  - { name: webstorm }
  - { name: keyboardcleantool }
  - { name: gimp }
  - { name: karabiner-elements }
  - { name: google-drive }
  - { name: flux }
  - { name: slack }
  - { name: visual-studio-code }
  - { name: vlc }
  - { name: charles }
  - { name: qfinder-pro }
  - { name: aerial }
  - { name: bitwarden }
  - { name: flutter }
  - { name: tableplus }
  - { name: tailscale }
  - { name: neohtop }
  - { name: firefox@nightly }
  - { name: jiggler }
  - { name: raspberry-pi-imager }
  - { name: azooKey }
  - { name: font-meslo-lg-nerd-font }
  - { name: claude-code }
  - { name: firefox }
  - { name: losslesscut }
  - { name: opencode-desktop }
  - { name: codex-app }
  - { name: android-commandlinetools }
